### ISSUE TITLE
Registration's related issues for recycler

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#1]
1. Address at the time of registration: Instead of giving single line in address tab there should be break down of address including column of PIN CODE, State etc. 

2. Field which are being filled in first stage should be auto populated in second stage at the time of document uploading.

3. Instead of having second page of document upload, we can ask all the details accept mandatory documents (PAN, GST, BANK DETAIL, CTE, CCA, PWM) in first page itself. Then we can land up on main page of Recycler or type of user. In that page user will be able to see some function but he need to verify himself to access full control (Just a suggestion).

4. Split Bank detail in 5 fields like: Bank Name, A/C Number, A/C Name, IFSC Code, Branch Name.

5. Valid upto (Date) accepting older date then current date. (Past date should not be accepted as valid date).

6. At the time of selecting date there was no option to select year or go to next year. Need to scroll through each month and every month. So if i need to enter a date after 5 year then i need to scroll 60 months. There should be option to write date in dd/mm/yy format or any one can select year directly.

7. Instead of having save button on top, there should be button of submit.

8. After final submission there is option of edit in top left side. But there is no clue about next step. Either we should go for back button or what ? Instead of going to back button we can ask for submit and after successful submission, Home page should be there ( no need to press back button ).

**Comment by prashantgithub82** [comment]
1. Address at the time of registration: Instead of giving single line in address tab there should be break down of address including column of PIN CODE, State etc.
**PR: Address field is now multiline and added State dropdown along with field for Pin Code.**

2. Field which are being filled in first stage should be auto populated in second stage at the time of document uploading.
**PR: DONE**

3. Instead of having second page of document upload, we can ask all the details accept mandatory documents (PAN, GST, BANK DETAIL, CTE, CCA, PWM) in first page itself. Then we can land up on main page of Recycler or type of user. In that page user will be able to see some function but he need to verify himself to access full control (Just a suggestion).
**PR: This flow we have designed purposefully to separate login detail and company detail. So first user create his credential, then login (with OTP verification) and then provide company details in authenticated environment.** 

4. Split Bank detail in 5 fields like: Bank Name, A/C Number, A/C Name, IFSC Code, Branch Name.
**PR: DONE**

5. Valid upto (Date) accepting older date then current date. (Past date should not be accepted as valid date).
**PR: In Progress - Will be tracked by separate bug.**

6. At the time of selecting date there was no option to select year or go to next year. Need to scroll through each month and every month. So if i need to enter a date after 5 year then i need to scroll 60 months. There should be option to write date in dd/mm/yy format or any one can select year directly.
**PR: This is default android calendar we have used. Please click on the year at top to select particular year and then you can navigate.**

7. Instead of having save button on top, there should be button of submit.
PR: This will be renamed to "Submit" and purpose of having it on top right is based on modern design approach.

8. After final submission there is option of edit in top left side. But there is no clue about next step. Either we should go for back button or what ? Instead of going to back button we can ask for submit and after successful submission, Home page should be there ( no need to press back button ).
PR: Yes, we are working on that flow; on click of submit, user will be redirected to listing page.

**Comment by 7597208625** [comment]
Point no. 5 is not resolved yet. At the time of registration if user adds any date for CTE or CCA, then also after save it takes current date and will show current date. If go for edit button then also it shows current date. 

please check.
