### ISSUE TITLE
Open Issues in App

### ISSUE THREAD

**Issue by prashantgithub82** [AppGrate/RecyclingSolutions-Issues#10]
1. After opening any shipment in transit -> go back -> try to do shipment "add" - throwing message "value can not be null".
2. On delete - it should first ask for confirmation and user should get redirected to listing page.
3. Shipment page is quite slow...
4. Listing pages are not getting refreshed automatically...

**Comment by 7597208625** [comment]
5. Approval page:
If admin decline any new request then also it ask to fill null values. In case of decline it does not make sense to ask admin to fill null values.

**Comment by 7597208625** [comment]
1. Please change name PBIO's to PIBO's. (My error)
2. PBIOs - > ADD -> Fill data -> Submit 
    After submission redirects to PBIOs page. But this page is not updated. It does not show the new user which was added. Only once we go back and come again to PBIOs page it will show that user. 
   If we add a new user then it should be there once completion of process.

3. Pdf document update function was not enabled.
4. There is fresh problem when we upload image in application. Screen shot shared over whats app.
5. There is message in blank page "-No items to display -", this message should not be there
6. There is lag in Purchase order page & Shipment page. Both pages are not smooth.

**Comment by 7597208625** [comment]
There should be at lease one user of each type of registered company in application i.e. PIBOs, Aggregator, Recyclers. 

As of current data in application there are two registered aggregators (1. Anish Polymer, 2. Pinnacle Industries). Admin page is not showing any user for both the aggregator. 

However, Anish Polymer & Pinnacle Industries were created by user registration method. So Anish Polymer can login in application via mobile number and password. But he can not create new shipment. 

User registration & Company registration are not in syc. If someone delete any company registration then it should automatically deactivate user and if admin create new company registration then there should be automatic user creation.

**Comment by 7597208625** [comment]
RAPDIUE RECYCLING - PIBO's Login

1. PIBO's can not create new purchase order. 
2. There is no company info tab. It means company info is not shown in PIBO's login. Only Profile tab is there which shows information about particular user. However, in case of aggregator login company info tab is there.

**Comment by prashantgithub82** [comment]
1. Approval page: If admin decline any new request then also it ask to fill null values. In case of decline it does not make sense to ask admin to fill null values. **FIXED**

2. Please change name PBIO's to PIBO's. **This will be big change; have to update everywhere in DB. So will do it in a day or two**

3. PBIOs - > ADD -> Fill data -> Submit. After submission redirects to PBIOs page. But this page is not updated. It does not show the new user which was added. Only once we go back and come again to PBIOs page it will show that user. If we add a new user then it should be there once completion of process. **IN-PROGRESS**

4. Pdf document update function was not enabled. **Required Discussion**

5. There is fresh problem when we upload image in application. Screen shot shared over what's app. **FIXED**

6. There is message in blank page "-No items to display -", this message should not be there. **FIXED**

7. There is lag in Purchase order page & Shipment page. Both pages are not smooth. **Slow because of app is in development mode. On Prod, it should be ok.**

8.0. There should be at lease one user of each type of registered company in application i.e. PIBOs, Aggregator, Recyclers. **This functionality is already there.**

8.1. As of current data in application there are two registered aggregators (1. Anish Polymer, 2. Pinnacle Industries). Admin page is not showing any user for both the aggregator.
**Users for corresponding company has been created during registration only but approval functionality was not working properly that time, so their status were still remain "Unverified", its been fixed now. Here is the credential for both: 9952433628 / asdf_1234, 7666513270 / asdf_1234**

8.2 However, Anish Polymer & Pinnacle Industries were created by user registration method. So Anish Polymer can login in application via mobile number and password. But he can not create new shipment. **FIXED**

8.3 User registration & Company registration are not in syc. If someone delete any company registration then it should automatically deactivate user and if admin create new company registration then there should be automatic user creation. **This should be working fine now.**

9. RAPDIUE RECYCLING - PIBO's Login. PIBO's can not create new purchase order. There is no company info tab. It means company info is not shown in PIBO's login. Only Profile tab is there which shows information about particular user. However, in case of aggregator login company info tab is there. **FIXED**

**Comment by 7597208625** [comment]
RAPDIUE RECYCLING - PIBO's Login. PIBO's can not create new purchase order. There is no company info tab. It means company info is not shown in PIBO's login. Only Profile tab is there which shows information about particular user. However, in case of aggregator login company info tab is there. FIXED

**This issue was not raised for particular PIBO's. It was raised because there is bug in application. Even for PIBO's application show two different page. 
This issue can repeat in future. Need proper solution.**

**Comment by 7597208625** [comment]
8.0. There should be at lease one user of each type of registered company in application i.e. PIBOs, Aggregator, Recyclers. This functionality is already there.

8.1. As of current data in application there are two registered aggregators (1. Anish Polymer, 2. Pinnacle Industries). Admin page is not showing any user for both the aggregator.
Users for corresponding company has been created during registration only but approval functionality was not working properly that time, so their status were still remain "Unverified", its been fixed now. Here is the credential for both: 9952433628 / asdf_1234, 7666513270 / asdf_1234

8.2 However, Anish Polymer & Pinnacle Industries were created by user registration method. So Anish Polymer can login in application via mobile number and password. But he can not create new shipment. FIXED

8.3 User registration & Company registration are not in syc. If someone delete any company registration then it should automatically deactivate user and if admin create new company registration then there should be automatic user creation. This should be working fine now.

**This issue was not raised for two particular user. It was raised because application showed random behavior. 
First and foremost point, if any registration is being created then immediately there should be automatic user creation for particular registration. In application there should be never a case where we see company registered but there is no user corresponding to that company registration. Even in case of unverified registration user should also be shown as unverified. 
This is a bug**

**Comment by prashantgithub82** [comment]
**All issues are closed...**
