### ISSUE TITLE
Aggregator creates the shipment

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#14]
1. Tag change: "Weigh Br Receipt" -> Quantity

2. Need to add a field "Type of Material". In type of material user should have option to select type of material from drop down list.
    As of now we are doing with with Plastic waste. So in drop down list there should be Plastic waste option. 
   
    In future when we start e-waste then drop down list shows: 1. Plastic waste, 2. E-waste 
     Like wise this list can be increased.

3. It is just a suggestion. E-way bill is electronically managed system and one can fetch e-way bill from E-way bill portal by QR code scan only. Can we look for this kind of facility where aggregator scan qr code and application take E-way bill detail from E-way bill server. Just think about this.

**Comment by 7597208625** [comment]
4. As discussed earlier one shipment can have multiple invoice number. There should be unique shipment number for a particular shipment and should be tracked by shipment number. Please check. 

5. There was problem when i tried to create a shipment second time. After successful shipment creation i was redirected to in transit page where i need to upload dispatch pictures. After submission of picture when i clicked Dispatch button, there was error as attached picture. 
![WhatsApp Image 2020-11-01 at 3 17 51 PM](https://user-images.githubusercontent.com/73227626/97799668-75422880-1c55-11eb-8475-8e8622344d25.jpeg)

If i go back then there was no data in shipment page. And if click edit button and try to add all the information again then application crashed. This is stability issue of application. Please check it. 

Due to this error ended up with creation of 2 shipment for same truck load. So here we have one more issue, if one aggregator creates two shipment with same invoice & e-way bill number then it should not be allowed.

**Comment by 7597208625** [comment]
6. There is significant lag when we click the picture and send it to "In Transit" chat box. From submission of picture (Click on symbol of right button after selection of appropriate picture) to the point where picture was shown in chat box total time was around 8 second. Please check.

**Comment by prashantgithub82** [comment]
1. Tag change: "Weigh Br Receipt" -> Quantity. **FIXED**

2. Need to add a field "Type of Material". In type of material user should have option to select type of material from drop down list. As of now we are doing with with Plastic waste. So in drop down list there should be Plastic waste option. In future when we start e-waste then drop down list shows: 1. Plastic waste, 2. E-waste. Like wise this list can be increased. **FIXED**

3. It is just a suggestion. E-way bill is electronically managed system and one can fetch e-way bill from E-way bill portal by QR code scan only. Can we look for this kind of facility where aggregator scan qr code and application take E-way bill detail from E-way bill server. Just think about this.
**We'll consider this as future item.**

4. **As discussed earlier and based on your suggestion - out of 2 approaches we opted for first option i.e. there will be separate shipment ID for separate invoice.**

5.1 There was problem when i tried to create a shipment second time. After successful shipment creation i was redirected to in transit page where i need to upload dispatch pictures. After submission of picture when i clicked Dispatch button, there was error as attached picture. **IN-PROGRESS**
5.2 If i go back then there was no data in shipment page. And if click edit button and try to add all the information again then application crashed. This is stability issue of application. Please check it. **IN-PROGRESS**
5.3 Due to this error ended up with creation of 2 shipment for same truck load. So here we have one more issue, if one aggregator creates two shipment with same invoice & e-way bill number then it should not be allowed. **FIXED**

6. There is significant lag when we click the picture and send it to "In Transit" chat box. From submission of picture (Click on symbol of right button after selection of appropriate picture) to the point where picture was shown in chat box total time was around 8 second. Please check.
**Currently we are in development phase, so testing is being done on low end servers. There should not be any issue once we move to Prod. We'll revisit these performance related issue during that time.**

**Comment by 7597208625** [comment]
4. As discussed earlier and based on your suggestion - out of 2 approaches we opted for first option i.e. there will be separate shipment ID for separate invoice.

**OK then please mark shipment properly for easy identification. Like with invoice number no tope - we can put aggregator initial in second line so user will have easy identification of shipment. As each aggregator will separate invoice number.**

![WhatsApp Image 2020-11-02 at 1 37 12 PM](https://user-images.githubusercontent.com/73227626/97844299-c95e1300-1d10-11eb-8743-6a71f9ecef94.jpeg)

**Comment by prashantgithub82** [comment]
**4. FIXED**

**5.1. FIXED**

**5.2. FIXED**

**Comment by 7597208625** [comment]
7. Shipment date: Shipment date should be current date or past date. Application is approving only current date or future date. Please ratify the same. Shipment date can be current date or past date.

**Comment by 7597208625** [comment]
Aggregator not able to create the shipment. 

![WhatsApp Image 2020-11-08 at 4 18 39 PM](https://user-images.githubusercontent.com/73227626/98462987-26a90700-21de-11eb-858f-d28ac51df738.jpeg)

**Comment by 7597208625** [comment]
8. Now shipment creation working.

**Comment by 7597208625** [comment]
8. Aggregator can not create shipment. I think this problem is due to driver detail. Followed this step to check the error.
   Step1: delete all driver user. So no driver user. Login with "GemCorp" user -> Created new shipment with a new driver user -> Shipment successful. and redirected to "Intransit" page.

   Step2: Login with different aggregator "ANISH POLYMER" -> create new shipment with same driver ("test") user as used before in "GEMCorp" -> error as picture attached. 
![WhatsApp Image 2020-11-08 at 4 37 49 PM](https://user-images.githubusercontent.com/73227626/98463373-d41d1a00-21e0-11eb-8d63-17a990fdcace.jpeg)
    Instead of error it should show a message that driver details are not correct. 

    Step 3: Login with aggregator "ANISH POLYMER" -> Create new shipment with new driver (different) user. -> Shipment successful.

**Comment by 7597208625** [comment]
Repeat same type of Problem mentioned in no. 5 (Mentioned 7 days ago)
Can not explain but errors shown as below. No user data, no data for intransit shipment. Please check.
![WhatsApp Image 2020-11-08 at 4 48 45 PM](https://user-images.githubusercontent.com/73227626/98463604-5b1ec200-21e2-11eb-9fdc-179b846391f5.jpeg)
![WhatsApp Image 2020-11-08 at 4 48 39 PM](https://user-images.githubusercontent.com/73227626/98463606-5e19b280-21e2-11eb-9694-f17a67819306.jpeg)

**Comment by prashantgithub82** [comment]
**All issues are fixed**

**Comment by 7597208625** [comment]
> 1. Shipment date: Shipment date should be current date or past date. Application is approving only current date or future date. Please ratify the same. Shipment date can be current date or past date.


Issue has been closed saying all issues are fixed. But this problem is still there. 

![WhatsApp Image 2020-11-20 at 4 35 13 PM](https://user-images.githubusercontent.com/73227626/99793297-72e53700-2b4e-11eb-8b96-98c84cb35038.jpeg)
