### ISSUE TITLE
Delay in shipment page

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#7]
There is significant lag in shipment page. Need to press each button 2-3 times to navigate through different system. 

Shipment page is not working properly. 

Please check.

**Comment by 7597208625** [comment]
In case of shipment creation there is option to select different Aggregators. 

It should show only approved aggregator rather than all aggregator. 

Please check.

**Comment by 7597208625** [comment]
At the time of creation of shipment there is option to select driver. 

As talked earlier driver login should be created at the time of shipment creation by mobile number. 

So instead of select driver there should be option to add Driver Number. 

Once shipment is created driver login will be created through that number only (if number exist in data base then it should show that number). 

please check.

**Comment by 7597208625** [comment]
In case of shipment if we select any Recycler from list then address of that Recycler should be shown in place of destination address. 

Please check.

**Comment by 7597208625** [comment]
After shipment creation there is chat box. 

Where admin can send a message. 

If admin a send a message over there the who can see that message ?

There is camera picture near by Send Message option. That camera picture is not working. 
There should be option to send loading picture of the truck.

**Comment by 7597208625** [comment]
After completion of shipment aggregator name is missing. 

Wanted to add screen shot but i don't know how to add picture here.

Bug.

**Comment by prashantgithub82** [comment]
1. There is significant lag in shipment page. Need to press each button 2-3 times to navigate through different system. Shipment page is not working properly. 
**This is in test version due to that it might be slow but will be working on its performance.**

2. In case of shipment creation there is option to select different Aggregators. It should show only approved aggregator rather than all aggregator. 
**In Progress**

3. At the time of creation of shipment there is option to select driver. As talked earlier driver login should be created at the time of shipment creation by mobile number. So instead of select driver there should be option to add Driver Number. Once shipment is created driver login will be created through that number only (if number exist in data base then it should show that number). 
**If that driver is already exists in database and associated with any other company (vendor); then will update its info with new one.**
**FIXED**

4. In case of shipment if we select any Recycler from list then address of that Recycler should be shown in place of destination address.
**In Progress**

5. After shipment creation there is chat box. Where admin can send a message. 
5.1. If admin a send a message over there the who can see that message?  **Vendor, Recycler, Driver associated with that shipment and Admin and Brand (once that shipment associated with PO) can view and chat through in-transit chatbox.**
5.2. There is camera picture near by Send Message option. That camera picture is not working. There should be option to send loading picture of the truck. **In Progress**

6. After completion of shipment aggregator name is missing. Wanted to add screen shot but i don't know how to add picture here. **FIXED**

**Comment by prashantgithub82** [comment]
2. In case of shipment creation there is option to select different Aggregators. It should show only approved aggregator rather than all aggregator. **FIXED**

4. In case of shipment if we select any Recycler from list then address of that Recycler should be shown in place of destination address. **In Progress**

5.2. There is camera picture near by Send Message option. That camera picture is not working. There should be option to send loading picture of the truck. **FIXED**

**Comment by prashantgithub82** [comment]
**All Items are fixed now...**
